### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by alexanderweide** [loki79uk/FS22_CabView#2]
Hey Loki,

first of all your Mod CabView is really essential and very important and i want to say thank you for this mod.

I want to ask if it would be possible to integrate a toggle button for the lean forward function. So when i press it once it will forward constantly , when i then press it again it will get back to normal mode. 

i am using evia cam head tracker to track my head and its really hard often to constantly push the shift button, It would be really nice to have a toggle button too.

Best Regards

Alex

**Comment by loki79uk** [comment]
Hi, yes this should not be difficult.  I think it is safer to add a different toggle-lean function which is unbound by default.  Then you can choose for yourself which keys are bound to momentary and/or toggle.  I could also do it like the double tap in LumberJack, but I think most people would not need this feature and it may get stuck in lean forward unintentionally.

**Comment by jason0611** [comment]
Hi, this feature would be great. Don't underestimate it. :-)

**Comment by loki79uk** [comment]
Hi, I've added an extra key binding, just re-bind shift if you don't need the momentary one.
https://github.com/loki79uk/FS22_CabView/releases/tag/v1.0.0.1

![image](https://user-images.githubusercontent.com/76516343/147419276-d09e9e04-4fa7-4dbe-a50b-97b4f57e45b4.png)

**Comment by alexanderweide** [comment]
Wow that fast. Thank you i will test this.. right now...

thank you.

**Comment by alexanderweide** [comment]
Works perfectly.. Thank you so much... The great thing is... my head tracker is just a easy headtracker that only tracks head rotation. This Cab View Mod makes the experience more realistic especially with a steering wheel. 

thank you.

**Comment by loki79uk** [comment]
No problem, glad you like it!

Let me know if you notice any weirdness with with FOV settings.  The story there is that originally I applied the FOV setting from the game menu to the internal cameras because I didn't like the new wide field view in the large vehicles (combines, etc).  Then I had a report that when you set a low FOV in the game settings, it became too distracting that the internal vs external camera had very different FOVs.  I'm pretty sure that no one will notice unless they use a very extreme (high or low) FOV.  It seems okay to me so far.

**Comment by alexanderweide** [comment]
I will do. Its saves my day. When something unusal is happening i will report it. this request can be closed.
